version: 2
updates:
  - package-ecosystem: "npm"
    directory: "client"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "api"
    schedule:
       interval: "daily"
